# Generated by Django 4.2.1 on 2023-06-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201223_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='film_genre', to='movies.Genre', verbose_name='Жанри'),
        ),
    ]
