# Generated by Django 4.2.1 on 2023-06-01 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20201223_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.DateField(default=datetime.date.today, verbose_name='Вік'),
        ),
    ]
