# Generated by Django 4.2.1 on 2023-06-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_actor_devorced'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='english_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Ім`я на англійській'),
        ),
    ]
