# Generated by Django 4.2.1 on 2023-06-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_actor_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='sum_movies',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Кількість фільмів'),
        ),
    ]
