# Generated by Django 4.2.1 on 2023-06-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_actor_sum_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='treiler',
            field=models.FileField(null=True, upload_to='treilers/', verbose_name='Трейлер'),
        ),
    ]
