# Generated by Django 4.2.1 on 2023-06-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_treiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='english_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва на англійській'),
        ),
    ]
