# Generated by Django 4.2.1 on 2023-06-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_english_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Найменування якості')),
            ],
            options={
                'verbose_name': 'Якість відео',
                'verbose_name_plural': 'Якість відео',
            },
        ),
    ]
