# Generated by Django 4.2.1 on 2023-06-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_qualityvideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='quality_videos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.qualityvideos', verbose_name='Якість відео'),
        ),
    ]
