# Generated by Django 4.2.1 on 2023-06-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movie_quality_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.ManyToManyField(related_name='film_producers', to='movies.Actor', verbose_name='Продюсер'),
        ),
    ]
