# Generated by Django 4.2.1 on 2023-06-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movie_ukrainian_premiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='devorced',
            field=models.ManyToManyField(blank=True, related_name='_actor_devorced_+', to='movies.Actor'),
        ),
    ]
